### ISSUE TITLE
Error: sortedGroups.flat is not a function

### ISSUE THREAD

**Issue by amenk** [trufi-association/osm-search-data-export#1]
Thanks for open sourcing this.

But I am getting an error:

	$ git clone https://github.com/trufi-association/osm-search-data-export

	$ cd osm-search-data-export

	$ yarn   # same error with npm install, but npm install showed some warnings

	$ ./cli.js --input pbf --inpath ~/test/Projects/trufi/osm/2019-08-31T01-03-01-addis-ababa.pbf --output json-compact --outpath out/
	/home/self/test/Projects/trufi/osm-search-data-export/src/transformer.js:286
		this.streetToNodes[street] = sortedGroups.flat();
		                                          ^

	TypeError: sortedGroups.flat is not a function
	    at Object.keys.forEach.street (/home/self/test/Projects/trufi/osm-search-data-export/src/transformer.js:286:51)
	    at Array.forEach (<anonymous>)
	    at Transformation.flattenStreetNodeGroups (/home/self/test/Projects/trufi/osm-search-data-export/src/transformer.js:268:8)
	    at Transformation.complete (/home/self/test/Projects/trufi/osm-search-data-export/src/transformer.js:62:10)
	    at onComplete (/home/self/test/Projects/trufi/osm-search-data-export/index.js:22:42)
	    at DestroyableTransform.fs.createReadStream.pipe.pipe.on (/home/self/test/Projects/trufi/osm-search-data-export/src/input/pbf.js:20:27)
	    at emitNone (events.js:111:20)
	    at DestroyableTransform.emit (events.js:208:7)
	    at finishMaybe (/home/self/test/Projects/trufi/osm-search-data-export/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:620:14)
	    at endWritable (/home/self/test/Projects/trufi/osm-search-data-export/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:629:3)

**Comment by amenk** [comment]
Similar, but different, with overpass

	$ ./cli.js --input overpass --bbox 38.61,8.8,38.96,9.13 --output json-compact --outpath out/
	(node:11259) UnhandledPromiseRejectionWarning: TypeError: relation.members.filter(...).map(...).filter(...).flatMap is not a function
	    at Transformation.processRelation (/home/self/test/Projects/trufi/osm-search-data-export/src/transformer.js:207:10)
	    at Transformation.addItem (/home/self/test/Projects/trufi/osm-search-data-export/src/transformer.js:55:14)
	    at onItem (/home/self/test/Projects/trufi/osm-search-data-export/index.js:21:35)
	    at Array.forEach (<anonymous>)
	    at result.then.items (/home/self/test/Projects/trufi/osm-search-data-export/src/input/overpass.js:37:28)
	    at <anonymous>
	    at process._tickCallback (internal/process/next_tick.js:188:7)
	(node:11259) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
	(node:11259) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by amenk** [comment]
Looks like I had an old Node version (8.x) - just upgraded to 12.x
