### ISSUE TITLE
polygon is required

### ISSUE THREAD

**Issue by leoguti** [trufi-association/osm-search-data-export#3]
Hi, tks for this scripts, now I'm trying to generate my search.json file, 

I update my node.js from 8 to 11 to avoid #1 issue, but now I have thi sissue 

osm-search-data-export --input pbf --inpath OSM/otp-duitama/duitama.osm.pbf --output json --outpath search.json
/home/leo/.npm-global/lib/node_modules/osm-search-data-export/node_modules/@turf/boolean-point-in-polygon/index.js:38
        throw new Error("polygon is required");
        ^

Error: polygon is required
    at booleanPointInPolygon (/home/leo/.npm-global/lib/node_modules/osm-search-data-export/node_modules/@turf/boolean-point-in-polygon/index.js:38:15)
    at Object.keys.find.name (/home/leo/.npm-global/lib/node_modules/osm-search-data-export/src/transformer.js:306:18)
    at Array.find (<anonymous>)
    at Object.keys.sort.forEach.street (/home/leo/.npm-global/lib/node_modules/osm-search-data-export/src/transformer.js:304:55)
    at Array.forEach (<anonymous>)
    at Transformation.extractStreets (/home/leo/.npm-global/lib/node_modules/osm-search-data-export/src/transformer.js:295:8)
    at Transformation.complete (/home/leo/.npm-global/lib/node_modules/osm-search-data-export/src/transformer.js:64:10)
    at onComplete (/home/leo/.npm-global/lib/node_modules/osm-search-data-export/index.js:22:42)
    at DestroyableTransform.fs.createReadStream.pipe.pipe.on (/home/leo/.npm-global/lib/node_modules/osm-search-data-export/src/input/pbf.js:20:27)
    at DestroyableTransform.emit (events.js:198:15)

**Comment by leoguti** [comment]
More details to recreate the error: 

$ node -v
v11.15.0


$ git clone https://github.com/trufi-association/osm-search-data-export

$ cd osm-search-data-export

$ yarn

$ /cli.js --input pbf --inpath ../OSM/otp-duitama/duitama.osm.pbf --output json-compact --outpath

./OSM/otp-duitama/duitama.osm.pbf --output json-compact --outpath search.json
/home/leo/osm-search-data-export/node_modules/@turf/boolean-point-in-polygon/index.js:38
        throw new Error("polygon is required");
        ^

Error: polygon is required
    at booleanPointInPolygon (/home/leo/osm-search-data-export/node_modules/@turf/boolean-point-in-polygon/index.js:38:15)
    at Object.keys.find.name (/home/leo/osm-search-data-export/src/transformer.js:306:18)
    at Array.find (<anonymous>)
    at Object.keys.sort.forEach.street (/home/leo/osm-search-data-export/src/transformer.js:304:55)
    at Array.forEach (<anonymous>)
    at Transformation.extractStreets (/home/leo/osm-search-data-export/src/transformer.js:295:8)
    at Transformation.complete (/home/leo/osm-search-data-export/src/transformer.js:64:10)
    at onComplete (/home/leo/osm-search-data-export/index.js:22:42)
    at DestroyableTransform.fs.createReadStream.pipe.pipe.on (/home/leo/osm-search-data-export/src/input/pbf.js:20:27)
    at DestroyableTransform.emit (events.js:198:15)
